version: '3.2'

services:
  dgraph-zero:
    image: dgraph/dgraph:v20.03.0
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 15080:5080
      - 16080:6080
    restart: always
    command: dgraph zero --my=dgraph-zero:5080
  dgraph-alpha:
    image: dgraph/dgraph:v20.03.0
    depends_on:
      - dgraph-zero
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 18080:8080
      - 19080:9080
    restart: always
    command: dgraph alpha --my=dgraph-alpha:7080 --lru_mb=2048 --zero=dgraph-zero:5080
  dgraph-ratel:
    image: dgraph/dgraph:v20.03.0
    depends_on:
      - dgraph-alpha
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 18000:8000
    restart: always
    command: dgraph-ratel

volumes:
  dgraph-data:
    driver: local
